const cron    = require("node-cron");
const Trip    = require("../models/tripModel.js");
const Seat    = require("../models/seatsModel.js");
const SeatTemplate = require("../models/seatTemplateModel.js");
const logger  = require("../utils/logger.js");

// ---------------------------------------------------------------------------
// Helper: initialise seat document for a newly generated trip
// ---------------------------------------------------------------------------
const initializeSeats = async (tripId, templateId) => {
    try {
        const template = await SeatTemplate.findById(templateId);
        if (!template) {
            logger.warn("TripCRON: seat template not found", { tripId, templateId });
            return;
        }
        await Seat.create({
            tripId,
            seata: template.seata.map(s => ({ seatNo: s.seatNo, booked: false })),
            seatb: template.seatb.map(s => ({ seatNo: s.seatNo, booked: false })),
            seatc: (template.seatc || []).map(s => ({ seatNo: s.seatNo, booked: false })),
        });
    } catch (e) {
        logger.error("TripCRON: failed to initialise seats", { tripId, error: e.message });
    }
};

// ---------------------------------------------------------------------------
// Trip auto-generation CRON  — runs daily at 00:00 server time
// Generates tomorrow's Trips from recurring BusSchedule templates
// ---------------------------------------------------------------------------
const setupTripGeneratorCron = () => {
    cron.schedule("0 0 * * *", async () => {
        logger.info("TripCRON: starting daily trip auto-generation");

        try {
            const now = new Date();

            // Build tomorrow's Date range (midnight-to-midnight UTC)
            // FIX: store tripDate as a proper Date object, NOT a string
            const tomorrowStart = new Date(now);
            tomorrowStart.setUTCDate(tomorrowStart.getUTCDate() + 1);
            tomorrowStart.setUTCHours(0, 0, 0, 0);

            const tomorrowEnd = new Date(tomorrowStart);
            tomorrowEnd.setUTCHours(23, 59, 59, 999);

            const dayOfWeek = tomorrowStart.getUTCDay(); // 0 (Sun) – 6 (Sat)

            // Fetch all active recurring template trips
            const templateTrips = await Trip.find({
                recurrence:       { $ne: "none" },
                autoGenerateUntil: { $gte: now },
                isActive:          true,
            });

            logger.info(`TripCRON: found ${templateTrips.length} recurring templates`);

            let generated = 0;
            let skipped   = 0;
            let errors    = 0;

            for (const trip of templateTrips) {
                try {
                    // Determine if tomorrow's day-of-week matches this template's schedule
                    let shouldGenerate = false;

                    if (trip.recurrence === "daily") {
                        shouldGenerate = true;
                    } else if (trip.recurrence === "weekly" || trip.recurrence === "custom") {
                        shouldGenerate = Array.isArray(trip.daysOfWeek) && trip.daysOfWeek.includes(dayOfWeek);
                    }

                    if (!shouldGenerate) continue;

                    // Idempotency check — use Date range query not string comparison
                    const exists = await Trip.findOne({
                        busId:          trip.busId,
                        routeId:        trip.routeId,
                        tripDate:       { $gte: tomorrowStart, $lte: tomorrowEnd },
                        departureTime:  trip.departureTime,
                        templateId:     trip._id.toString(),
                    });

                    if (exists) {
                        logger.debug("TripCRON: trip already exists for tomorrow — skipping", {
                            templateId: trip.tripId,
                        });
                        skipped++;
                        continue;
                    }

                    // Create the new trip for tomorrow — tripDate stored as Date
                    const newTripId = `TRIP-${Date.now()}-${Math.floor(Math.random() * 1000)}`;
                    const newTrip = await Trip.create({
                        tripId:          newTripId,
                        busId:           trip.busId,
                        routeId:         trip.routeId,
                        ownerId:         trip.ownerId,
                        driverId:        trip.driverId || null,
                        tripDate:        tomorrowStart,      // ← Date object, not string
                        departureTime:   trip.departureTime,
                        arrivalTime:     trip.arrivalTime,
                        tripFare:        trip.tripFare,
                        seatTemplateId:  trip.seatTemplateId,
                        isAutoGenerated: true,
                        templateId:      trip._id.toString(),
                        status:          "scheduled",
                        recurrence:      "none",             // prevent recursive generation
                        shift:           trip.shift,
                        isActive:        true,
                    });

                    await initializeSeats(newTrip._id, trip.seatTemplateId);

                    logger.info("TripCRON: generated new trip", {
                        tripId:    newTrip.tripId,
                        date:      tomorrowStart.toISOString().split("T")[0],
                        busId:     trip.busId,
                        routeId:   trip.routeId,
                    });
                    generated++;

                } catch (innerErr) {
                    logger.error("TripCRON: error processing template trip", {
                        templateTripId: trip.tripId,
                        error: innerErr.message,
                    });
                    errors++;
                }
            }

            logger.info("TripCRON: completed", { generated, skipped, errors });

        } catch (error) {
            logger.error("TripCRON: fatal error in auto-generation job", { error: error.message });
        }
    });

    logger.info("TripCRON: scheduled — runs daily at 00:00 server time");
};

module.exports = setupTripGeneratorCron;
