const cron = require("node-cron");
const Trip = require("../models/tripModel.js");
const Seat = require("../models/seatsModel.js");
const seatTemplateModel = require("../models/seatTemplateModel.js");
const moment = require("moment"); // Ensure moment is available

// Helper to initialize seats based on a template
const initializeSeats = async (tripId, templateId) => {
    try {
        const template = await seatTemplateModel.findById(templateId);
        if (!template) {
            console.error(`Seat template ${templateId} not found for trip ${tripId}`);
            return;
        }

        await Seat.create({
            tripId: tripId,
            seata: template.seata.map(s => ({ seatNo: s.seatNo, booked: false })),
            seatb: template.seatb.map(s => ({ seatNo: s.seatNo, booked: false })),
            seatc: template.seatc ? template.seatc.map(s => ({ seatNo: s.seatNo, booked: false })) : []
        });
    } catch (e) {
        console.error(`Error initializing seats for trip ${tripId}:`, e.message);
    }
};

const setupTripGeneratorCron = () => {
    // Run exactly at midnight server time every day
    cron.schedule("0 0 * * *", async () => {
        console.log("CRON: Running trip auto-generation task...");
        try {
            const now = new Date();
            const tomorrowStr = moment(now).add(1, 'days').format("YYYY-MM-DD");
            
            // Find template trips. We consider the trips created by the user where recurrence != none as "templates"
            const templateTrips = await Trip.find({
                recurrence: { $ne: "none" },
                autoGenerateUntil: { $gte: now },
                isActive: true
            });

            console.log(`CRON: Found ${templateTrips.length} active recurring trips.`);

            for (const trip of templateTrips) {
                // Check if tomorrow matches the rules
                let shouldGenerate = false;
                const nextDay = moment(now).add(1, 'days');
                const dayOfWeek = nextDay.day(); // 0(Sun) - 6(Sat)

                if (trip.recurrence === "daily") {
                    shouldGenerate = true;
                } else if (trip.recurrence === "weekly" || trip.recurrence === "custom") {
                    if (trip.daysOfWeek && trip.daysOfWeek.includes(dayOfWeek)) {
                        shouldGenerate = true;
                    }
                }

                if (shouldGenerate) {
                    // Check if trip already exists for tomorrow
                    const exists = await Trip.findOne({
                        busId: trip.busId,
                        routeId: trip.routeId,
                        tripDate: tomorrowStr,
                        departureTime: trip.departureTime,
                        templateId: trip._id.toString()
                    });

                    if (!exists) {
                        const newTripId = `TRIP-${Date.now()}-${Math.floor(Math.random() * 1000)}`;
                        
                        const newTrip = await Trip.create({
                            tripId: newTripId,
                            busId: trip.busId,
                            routeId: trip.routeId,
                            ownerId: trip.ownerId,
                            driverId: trip.driverId,
                            tripDate: tomorrowStr,
                            departureTime: trip.departureTime,
                            arrivalTime: trip.arrivalTime,
                            tripFare: trip.tripFare,
                            seatTemplateId: trip.seatTemplateId,
                            isAutoGenerated: true,
                            templateId: trip._id.toString(), // Store parent reference
                            status: "scheduled",
                            recurrence: "none", // Prevent recursive generation
                            shift: trip.shift,
                            isActive: true
                        });
                        
                        await initializeSeats(newTrip._id, trip.seatTemplateId);
                        console.log(`CRON: Generated new trip ${newTrip.tripId} for date ${tomorrowStr}`);
                        
                        // FUTURE: Send Notification to Owner
                    } else {
                        console.log(`CRON: Trip for ${tomorrowStr} already exists for template ${trip.tripId}`);
                    }
                }
            }
        } catch (error) {
            console.error("CRON Error: Failed to auto-generate trips:", error);
        }
    });

    console.log("CRON: Trip auto-generation scheduled (runs daily at 00:00).");
};

module.exports = setupTripGeneratorCron;
