const express = require("express");
const router = express.Router();
const admin = require("../../src/modules/admin/user-management");
const bookings = require("../../controllers/adminController/booking/bookingController.js");
const couponAdminRoutes = require("../../src/modules/coupon/admin");
const autoSeat = require("../../controllers/adminController/seat-controller/adminAutoSeatController.js");
const authController = require("../../controllers/adminController/authController/auth-controller.js");
const { adminEnrollmentLimiter, adminLoginLimiter } = require("../../middleware/adminAuthRateLimit.js");
const adminMiddleware = require("../../middleware/adminMiddleware.js");
const rootAdminMiddleware = require("../../middleware/rootAdminMiddleware.js");
const adminAdministration = require("../../src/modules/admin/auth-security/admin-administration.controller.js");
const dashboard = require("../../controllers/adminController/dashboardController/dashboardController.js");
const userDashboard = require("../../controllers/adminController/dashboardController/userDashboardController.js");
const agentConversion = require("../../src/modules/agent/admin/conversion");
const agentDirectory = require("../../src/modules/agent/admin/directory");
const agentDashboard = require("../../src/modules/agent/admin/dashboard");
const agentSetup = require("../../src/modules/agent/admin/setup");
const agentKycReview = require("../../src/modules/kyc/agent-review");
const busOwnerController = require("../../src/modules/admin/bus-owner-management");
const adminPushnotification = require("../../controllers/adminController/adminPushnotification.js/adminPushnotification.js");
const busOwnerFleetController = require("../../src/modules/admin/fleet-management");
const refundController = require("../../controllers/adminController/refundController/adminRefundController.js");
const refundPolicyController = require("../../controllers/adminController/refundPolicyController/refundPolicycontroller.js");
const kycVerificationController = require("../../controllers/adminController/kycVerificationController/kycVerificationcontroller.js");
const ticketController = require("../../src/modules/admin/ticket-schedule-management");
const boardingPointController = require("../../controllers/adminController/ticket-controller/adminBoardingPoinController.js");
const adminAmenityController = require("../../controllers/adminController/amenity/amenityController.js");
const adminBusRouteController = require("../../controllers/adminController/busOwnerController/busRouteController.js");
const adminFleetController = require("../../controllers/adminController/busOwnerController/fleetController.js");
const { adminFleetDocumentController } = require("../../src/modules/fleet/document-lifecycle");
const {
  notifyAdminCreatedFleet,
} = require("../../src/modules/admin/fleet-management/admin-fleet-created-notification.controller");
const adminTemplateController = require("../../controllers/adminController/busOwnerController/templateController.js");
const adminTripController = require("../../controllers/adminController/busOwnerController/tripController.js");
const adminSettlementCon = require("../../controllers/busOwnerController/settlementController.js");
const fareRuleCon = require("../../controllers/busOwnerController/fareRuleController.js");
const commissionController = require("../../controllers/adminController/commissionController/commissionController.js");
const financialController  = require("../../src/modules/admin/financial-overview");
const analyticsController  = require("../../controllers/adminController/analyticsController/analyticsController.js");
const platformRegistry     = require("../../src/modules/admin/platform-registry");
const operatorConfig       = require("../../src/modules/admin/operator-route-configuration");
const operatorBrand        = require("../../controllers/adminController/operatorBrandController.js");
const routeRequestCtrl     = require("../../controllers/adminController/routeRequestController.js");
const scheduleController   = require("../../src/modules/admin/schedule-management");
const tripExceptionCtrl    = require("../../controllers/adminController/tripExceptionController.js");
const brandFinancialCtrl   = require("../../controllers/adminController/brandFinancialController.js");
const driverController     = require("../../controllers/adminController/driverController.js");
const fleetWorkstation     = require("../../src/modules/admin/fleet-workstation");
const tripOverviewCtrl     = require("../../src/modules/admin/trip-overview");
const adminWalletCtrl      = require("../../src/modules/admin/wallet-management");
const transactionCtrl      = require("../../controllers/adminController/transactionController/transactionController.js");
const registryBoardingRoutes = require("./registryBoardingRoutes.js");
const { registerAdminSeatLayoutV3Routes } = require("./seatLayoutV3Routes.js");
const { rejectOversizedKycRequest, parseKycSubmissionUpload } = require("../../middleware/kycSubmissionUpload.js");
router.post("/auth/login", adminLoginLimiter, authController.login);
router.post("/auth/bootstrap/mfa/begin", adminEnrollmentLimiter, authController.beginBootstrapMfa);
router.post("/auth/bootstrap/mfa/confirm", adminEnrollmentLimiter, authController.confirmBootstrapMfa);
router.post("/auth/invitations/mfa/begin", adminEnrollmentLimiter, adminAdministration.begin);
router.post("/auth/invitations/mfa/confirm", adminEnrollmentLimiter, adminAdministration.confirm);
router.get("/auth/profile",  adminMiddleware, authController.getAdminProfile);
router.get("/administrators", adminMiddleware, rootAdminMiddleware, adminAdministration.list);
router.post("/administrators/invitations", adminMiddleware, rootAdminMiddleware, adminAdministration.invite);
router.patch("/administrators/:adminId/status", adminMiddleware, rootAdminMiddleware, adminAdministration.updateStatus);
router.delete("/deleteAccount", adminMiddleware, admin.deleteAccount);
router.get("/getAllUsers", adminMiddleware, admin.getAllUsers);
router.get("/userDashboard", adminMiddleware, userDashboard.getUserDashboardStats);
router.post("/getuserById", adminMiddleware, admin.getUserById);
router.patch("/resetPassword", adminMiddleware, admin.changeUserPassword);
router.patch("/updateStatus", adminMiddleware, admin.updateUserStatus);
router.get("/users/:id/transactions", adminMiddleware, admin.getUserTransactions);
router.get("/getAllTicket", adminMiddleware, ticketController.getAllTickets);
router.post("/auto-seats", adminMiddleware, autoSeat.createAutoSeat);
router.get("/booking/getAllBookings", adminMiddleware, bookings.getAllBookings);
router.get("/booking/stats", adminMiddleware, bookings.getBookingStats);
router.get("/booking/getBookingById/:bookingid", adminMiddleware, bookings.getBookingById);
router.post("/booking/getBookingsByUser", adminMiddleware, bookings.getBookingsByUser);
router.use(couponAdminRoutes);
router.get("/dashboard", adminMiddleware, dashboard.getDashboardStats);
router.get("/userdashboard", adminMiddleware, userDashboard.getUserDashboardStats);
router.post("/getAgentDetails", adminMiddleware, agentDirectory.getAgentsById);
router.get("/getAllAgents", adminMiddleware, agentDirectory.getAllAgents);
router.get("/agentDashboard", adminMiddleware, agentDashboard.getAgentDashboard);
router.post("/makeUserAgent", adminMiddleware, agentConversion.makeUserAgent);
router.patch("/finalizeAgentSetup", adminMiddleware, agentSetup.finalizeAgentSetup);
router.patch("/agentKycStatus", adminMiddleware, agentKycReview.updateAgentKyc);
const { registerAdminFrontendReadRoutes } = require("./frontendReadRoutes.js");
registerAdminFrontendReadRoutes(router);
router.post("/busOwner/create", adminMiddleware, rejectOversizedKycRequest, parseKycSubmissionUpload, busOwnerController.createBusOwnerFull);
router.post(
  "/busOwner/:userId/access-notification/resend",
  adminMiddleware,
  require("../../middleware/adminOwnerAccessRateLimit"),
  busOwnerController.resendOwnerAccess
);
router.post("/busOwner/reuploadKycDocument", adminMiddleware, rejectOversizedKycRequest, parseKycSubmissionUpload, busOwnerController.reuploadKycDocument);
router.patch("/busOwnerKycStatus", adminMiddleware, busOwnerController.updateBusOwnerKyc);
router.patch("/busOwner/update", adminMiddleware, busOwnerController.updateBusOwnerProfile);
router.get("/busOwnerDashboard", adminMiddleware, busOwnerController.getBusOwnerDashboard);
const kycDocumentRead = require("../../src/modules/bus-owner/kyc-document-read");
router.get("/busOwner/kycDocumentReadUrl", adminMiddleware, kycDocumentRead.getKycDocumentReadUrl);
router.get("/busOwner/kycDocumentView", adminMiddleware, kycDocumentRead.viewKycDocument);
router.post(
  "/push/sendAll",
  adminMiddleware,
  adminPushnotification.sendAllUserToPushnotification
);
router.post(
  "/push/sendOne",
  adminMiddleware,
  adminPushnotification.sendSingleUserToPushnotification
);
router.patch("/fleet/update-status",    adminMiddleware, busOwnerFleetController.updateFleetStatus);
router.patch("/fleet/:fleetId/reviews/:key", adminMiddleware, busOwnerFleetController.saveFleetReviewItem);
router.get('/fleet/fleetDashboard',     adminMiddleware, busOwnerFleetController.getFleetDashboard);
router.get("/fleet/:id/workstation",                      adminMiddleware, fleetWorkstation.getFleetWorkstation);
router.get("/fleet/:fleetId/trips/:tripId/manifest",      adminMiddleware, fleetWorkstation.getTripManifest);
router.patch("/fleet/:fleetId/trips/:tripId/status",      adminMiddleware, fleetWorkstation.updateTripStatus);
router.patch("/fleet/:fleetId/trips/:tripId/driver",      adminMiddleware, fleetWorkstation.reassignTripDriver);
router.get("/refund/queue", adminMiddleware, refundController.getRefundQueue);
router.get("/refund/getAllCancelledBookings", adminMiddleware, refundController.getRefundQueue); // legacy alias
router.patch("/refund/update-status", adminMiddleware, refundController.updateRefundStatus);
router.post("/refund-policy/create", adminMiddleware, refundPolicyController.createRefundPolicy);
router.get("/refund-policy/getAll", adminMiddleware, refundPolicyController.getAllRefundPolicies);
router.post("/refund-policy/getById", adminMiddleware, refundPolicyController.getRefundPolicyById);
router.patch("/refund-policy/update", adminMiddleware, refundPolicyController.updateRefundPolicy);
router.delete("/refund-policy/delete", adminMiddleware, refundPolicyController.deleteRefundPolicy);
router.patch("/refund-policy/toggleStatus", adminMiddleware, refundPolicyController.togglePolicyStatus);
router.get("/wallet/overview",              adminMiddleware, adminWalletCtrl.getOverview);
router.get("/wallet/global-feed",           adminMiddleware, adminWalletCtrl.getGlobalFeed);
router.get("/wallet/lookup",                adminMiddleware, adminWalletCtrl.lookupUser);
router.post("/wallet/adjust",               adminMiddleware, adminWalletCtrl.adjustBalance);
router.patch("/wallet/freeze",              adminMiddleware, adminWalletCtrl.freezeWallet);
router.get("/wallet/user-balance/:userId",  adminMiddleware, adminWalletCtrl.getUserBalance);
router.get("/kyc/unified-list", adminMiddleware, kycVerificationController.getUnifiedKycList);
router.delete("/ticket/schedule/delete/:id", adminMiddleware, ticketController.deleteTicket);
router.get("/templates/all", adminMiddleware, adminTemplateController.getAllSeatsTemplate);
router.get("/templates/user/:userId", adminMiddleware, adminTemplateController.getTemplatesByUser);
router.get("/templates/:id", adminMiddleware, adminTemplateController.getSeatTemplateById);
registerAdminSeatLayoutV3Routes(router, adminMiddleware);
router.post("/ticket/create-route", adminMiddleware, ticketController.createRoute);
router.get("/ticket/getAllRoutes", adminMiddleware, ticketController.getAllRoutes);
router.get("/ticket/getRouteById/:id", adminMiddleware, ticketController.getRouteById);
router.patch("/ticket/updateRoute/:id", adminMiddleware, ticketController.updateRoute);
router.delete("/ticket/deleteRoute/:id", adminMiddleware, ticketController.deleteRoute);
router.patch("/ticket/toggleRouteStatus/:id", adminMiddleware, ticketController.toggleRouteStatus);
router.post("/ticket/createTicket", adminMiddleware, ticketController.createTicket);
router.get("/ticket/getTicketById/:id", adminMiddleware, ticketController.getTicketById);
router.patch("/ticket/updateTicket/:id", adminMiddleware, ticketController.updateTicket);
router.patch("/ticket/updateTicketStatus/:id", adminMiddleware, ticketController.updateTicketStatus);
router.delete("/ticket/deleteTicket/:id", adminMiddleware, ticketController.deleteTicket);
router.post("/ticket/amenities/create", adminMiddleware, (_req, res) => res.status(410).json({
  success: false,
  message: "Amenity groups are retired. Use the platform or operator amenity catalog.",
  errorCode: "LEGACY_AMENITY_API_RETIRED",
}));
/* 
170: router.get("/ticket/amenities/getAll", adminMiddleware, amenitiesController.getAllAmenities);
171: router.get("/ticket/amenities/getById/:id", adminMiddleware, amenitiesController.getAmenityById);
172: router.get("/ticket/amenities/getByUserId/:userId", adminMiddleware, amenitiesController.getAmenitiesByUserId);
173: router.patch("/ticket/amenities/bulk-update", adminMiddleware, amenitiesController.bulkUpdateAmenities);
174: router.delete("/ticket/amenities/delete/:amenityId/:userId", adminMiddleware, amenitiesController.deleteAmenity);
175: router.patch("/ticket/amenities/toggleStatus/:id", adminMiddleware, amenitiesController.toggleAmenityStatus);
*/
/*
177: router.post("/ticket/boardingPoint/create", adminMiddleware, boardingPointController.createBoardingPoint);
178: router.get("/ticket/boardingPoint/getAll", adminMiddleware, boardingPointController.getAllBoardingPoints);
179: router.get("/ticket/boardingPoint/getById/:id", adminMiddleware, boardingPointController.getBoardingPointById);
180: router.patch("/ticket/boardingPoint/update/:id", adminMiddleware, boardingPointController.updateBoardingPoint);
181: router.delete("/ticket/boardingPoint/delete/:id", adminMiddleware, boardingPointController.deleteBoardingPoint);
182: router.patch("/ticket/boardingPoint/toggleStatus/:id", adminMiddleware, boardingPointController.toggleBoardingPointStatus);
*/
router.post("/boardingPoints/create", adminMiddleware, boardingPointController.createBoardingPoint);
router.get("/boardingPoints/city/:city", adminMiddleware, boardingPointController.getPointsByCity);
router.get("/boardingPoints/owner/:ownerId", adminMiddleware, boardingPointController.getPointsByOwner);
router.get("/boardingPoints/:id", adminMiddleware, boardingPointController.getBoardingPointById);
router.patch("/boardingPoints/:id", adminMiddleware, boardingPointController.updateBoardingPoint);
router.delete("/boardingPoints/:id", adminMiddleware, boardingPointController.deleteBoardingPoint);
router.get("/amenities/global", adminMiddleware, adminAmenityController.getAllGlobalAmenities);
router.post("/amenities/createGlobal", adminMiddleware, adminAmenityController.createGlobalAmenity);
router.post("/amenities/create", adminMiddleware, adminAmenityController.createAmenityForOwner);
router.get("/amenities/owner/:ownerId/custom", adminMiddleware, adminAmenityController.getOwnerCustomAmenities);
router.get("/amenities/owner/:ownerId", adminMiddleware, adminAmenityController.getAvailableAmenities);
router.get("/amenities/:id", adminMiddleware, adminAmenityController.getAmenityById);
router.patch("/amenities/:id", adminMiddleware, adminAmenityController.updateAmenity);
router.delete("/amenities/:id", adminMiddleware, adminAmenityController.deleteAmenity);
router.post("/busRoutes/create", adminMiddleware, adminBusRouteController.createRouteForOwner);
router.post("/busRoutes/createGlobal", adminMiddleware, adminBusRouteController.createGlobalRoute);
router.get("/busRoutes/global", adminMiddleware, adminBusRouteController.getGlobalRoutes);
router.get("/busRoutes/owner/:ownerId", adminMiddleware, adminBusRouteController.getRoutesByOwner);
router.get("/busRoutes/:id", adminMiddleware, adminBusRouteController.getRouteById);
router.patch("/busRoutes/:id", adminMiddleware, adminBusRouteController.updateRouteByAdmin);
router.delete("/busRoutes/:id", adminMiddleware, adminBusRouteController.deleteRouteByAdmin);
router.post("/fleet/createForOwner", adminMiddleware, adminFleetController.createFleetForOwner);
router.post(
  "/fleet/:fleetId/notify-created",
  adminMiddleware,
  require("../../middleware/adminFleetNotificationRateLimit"),
  notifyAdminCreatedFleet
);
router.get("/fleet/owner/:ownerId", adminMiddleware, adminFleetController.getFleetsByOwner);
router.patch("/fleet/update/:id", adminMiddleware, adminFleetController.updateFleetByAdmin);
router.delete("/fleet/delete/:id", adminMiddleware, adminFleetController.deleteFleetByAdmin);
router.patch("/fleet/reupload-doc/:id", adminMiddleware, adminFleetController.reuploadFleetDocument);
router.put("/fleet/:fleetId/documents/:slot", adminMiddleware, adminFleetDocumentController.uploadDocument);
router.get("/fleet/:fleetId/documents/:slot/read-url", adminMiddleware, adminFleetDocumentController.getDocumentReadUrl);
router.get("/fleet/:fleetId/documents/:slot/view", adminMiddleware, adminFleetDocumentController.viewDocument);
router.get("/trips/overview",          adminMiddleware, tripOverviewCtrl.getOverview);
router.get("/trips/schedule-health",   adminMiddleware, tripOverviewCtrl.getScheduleHealth);
router.get("/trips/search",            adminMiddleware, tripOverviewCtrl.searchTrips);
router.get("/trips/route-performance", adminMiddleware, tripOverviewCtrl.getRoutePerformance);
router.post("/trips/create",               adminMiddleware, adminTripController.createTripForOwner);
router.get("/trips/all",                   adminMiddleware, adminTripController.getAllTrips);
router.get("/trips/owner/:ownerId",        adminMiddleware, adminTripController.getTripsByOwner);
router.get("/trips/details/:id",           adminMiddleware, adminTripController.getTripById);
router.patch("/trips/update/:id",          adminMiddleware, adminTripController.updateTripByAdmin);
router.patch("/trips/status/:id",          adminMiddleware, adminTripController.updateTripStatusByAdmin);
router.delete("/trips/delete/:id",         adminMiddleware, adminTripController.deleteTripByAdmin);
router.patch("/trips/assign-driver/:id",   adminMiddleware, adminTripController.assignDriverToTrip);
router.post("/drivers",                    adminMiddleware, driverController.createDriver);
router.get("/drivers",                     adminMiddleware, driverController.getAllDrivers);
router.get("/drivers/:id",                 adminMiddleware, driverController.getDriverById);
router.patch("/drivers/:id",               adminMiddleware, driverController.updateDriver);
router.patch("/drivers/:id/approve",       adminMiddleware, driverController.approveDriver);
router.patch("/drivers/:id/reject",        adminMiddleware, driverController.rejectDriver);
router.patch("/drivers/:id/assign-bus",    adminMiddleware, driverController.assignBusToDriver);
router.get("/brands/:brandId/drivers",     adminMiddleware, driverController.getDriversByBrand);
router.get("/settlements/all", adminMiddleware, adminSettlementCon.getMySettlements);
router.patch("/settlements/pay", adminMiddleware, adminSettlementCon.paySettlement);
router.get("/commissions/summary", adminMiddleware, commissionController.getCommissionSummary);
router.get("/commissions/history", adminMiddleware, commissionController.getCommissionHistory);
router.get("/financial/overview", adminMiddleware, financialController.getFinancialOverview);
router.get("/analytics/overview", adminMiddleware, analyticsController.getAnalyticsOverview);
router.post("/registry/stops/bulk-preview", adminMiddleware, platformRegistry.previewBulkImportStops);
router.post("/registry/stops/bulk-import",  adminMiddleware, platformRegistry.bulkImportStops);
router.post("/registry/stops",            adminMiddleware, platformRegistry.createStop);
router.get("/registry/stops",             adminMiddleware, platformRegistry.getAllStops);
router.get("/registry/stops/search",      adminMiddleware, platformRegistry.searchStops);
router.patch("/registry/stops/:id",       adminMiddleware, platformRegistry.updateStop);
router.delete("/registry/stops/:id",      adminMiddleware, platformRegistry.deleteStop);
router.post("/registry/corridors",        adminMiddleware, platformRegistry.createCorridor);
router.get("/registry/corridors",         adminMiddleware, platformRegistry.getAllCorridors);
router.patch("/registry/corridors/:id",   adminMiddleware, platformRegistry.updateCorridor);
router.delete("/registry/corridors/:id",  adminMiddleware, platformRegistry.deleteCorridor);
router.post("/registry/variants",                          adminMiddleware, platformRegistry.createVariant);
router.get("/registry/corridors/:corridorId/variants",    adminMiddleware, platformRegistry.getVariantsByCorridor);
router.get("/registry/variants/:id",                     adminMiddleware, platformRegistry.getVariantDetails);
router.post("/registry/variants/:id/revisions",          adminMiddleware, platformRegistry.createVariantRevision);
router.post("/registry/variants/:id/repair-pair",        adminMiddleware, platformRegistry.repairVariantPair);
router.post("/registry/variants/:id/retire-pair",        adminMiddleware, platformRegistry.retireVariantPair);
router.post("/registry/variants/:id/rollback",           adminMiddleware, platformRegistry.rollbackVariantRevision);
router.delete("/registry/variants/:id/history",          adminMiddleware, platformRegistry.deleteHistoricalRevision);
router.patch("/registry/variants/:id",                    adminMiddleware, platformRegistry.updateVariant);
router.delete("/registry/variants/:id",                   adminMiddleware, platformRegistry.deleteVariant);
router.post("/registry/corridors/:corridorId/route-preview", adminMiddleware, platformRegistry.previewCorridorRoutePaths);
router.post("/registry/corridors/:corridorId/variant-drafts", adminMiddleware, platformRegistry.createVariantDraft);
router.get("/registry/variant-drafts/:variantId", adminMiddleware, platformRegistry.getVariantDraft);
router.post("/registry/variant-drafts/:variantId/route-options", adminMiddleware, platformRegistry.refreshVariantDraftRouteOptions);
router.get("/registry/variant-drafts/:variantId/guidance-places", adminMiddleware, platformRegistry.searchVariantDraftGuidancePlaces);
router.patch("/registry/variant-drafts/:variantId/select-route", adminMiddleware, platformRegistry.selectVariantDraftRouteOption);
router.patch("/registry/variant-drafts/:variantId/details", adminMiddleware, platformRegistry.updateVariantDraftDetails);
router.post("/registry/variant-drafts/:variantId/stop-candidates", adminMiddleware, platformRegistry.prepareVariantDraftStopCandidates);
router.post("/registry/variant-drafts/:variantId/stop-candidates/manual", adminMiddleware, platformRegistry.addExistingVariantDraftStop);
router.patch("/registry/variant-drafts/:variantId/stop-candidates/use-existing", adminMiddleware, platformRegistry.useAllMatchedVariantDraftCandidates);
router.patch("/registry/variant-drafts/:variantId/stop-candidates/:candidateId", adminMiddleware, platformRegistry.updateVariantDraftCandidate);
router.post("/registry/variant-drafts/:variantId/commit", adminMiddleware, platformRegistry.commitVariantDraft);
router.post("/registry/variant-drafts/:variantId/activate", adminMiddleware, platformRegistry.activateVariantDraft);
router.put("/registry/variants/:variantId/stops",  adminMiddleware, platformRegistry.setVariantStops);
router.get("/registry/variants/:variantId/stops",  adminMiddleware, platformRegistry.getStopsForVariant);
router.use("/registry", registryBoardingRoutes);
router.get("/registry/route-requests",         adminMiddleware, routeRequestCtrl.getAllRouteRequests);
router.get("/registry/route-requests/:id",     adminMiddleware, routeRequestCtrl.getRouteRequestById);
router.patch("/registry/route-requests/:id",   adminMiddleware, routeRequestCtrl.reviewRouteRequest);
router.get("/operator-config/variants",                                       adminMiddleware, operatorConfig.getAvailableVariants);
router.get("/operator-config/:brandId",                                     adminMiddleware, operatorConfig.getOperatorConfigs);
router.get("/operator-config/:brandId/variant/:variantId/stops",           adminMiddleware, operatorConfig.getVariantStopsWithConfig);
router.get("/operator-config/:brandId/variant/:variantId/return-stops",    adminMiddleware, operatorConfig.getReturnVariantStops);
router.get("/operator-config/:brandId/variant/:variantId/patterns",        adminMiddleware, operatorConfig.listPatternsForVariant);
router.post("/operator-config",                                                adminMiddleware, operatorConfig.upsertOperatorConfig);
router.patch("/operator-config/:configId",                                   adminMiddleware, operatorConfig.updateConfig);
router.patch("/operator-config/:configId/status",                           adminMiddleware, operatorConfig.toggleConfigStatus);
router.patch("/operator-config/:configId/set-default",                      adminMiddleware, operatorConfig.setDefaultPattern);
router.delete("/operator-config/:configId",                                  adminMiddleware, operatorConfig.deleteConfig);
router.get("/brands/:brandId/route-services",                               adminMiddleware, operatorConfig.getBrandRouteServices);
router.post("/brands",                              adminMiddleware, operatorBrand.createBrand);
router.get("/brands",                               adminMiddleware, operatorBrand.getAllBrands);
router.get("/brands/:brandId",                      adminMiddleware, operatorBrand.getBrandById);
router.get("/owners/:ownerId/brands",               adminMiddleware, operatorBrand.getBrandsByOwner);
router.patch("/brands/:brandId/status",             adminMiddleware, operatorBrand.updateBrandStatus);
router.patch("/brands/:brandId",                    adminMiddleware, operatorBrand.updateBrand);
router.get("/brands/:brandId/financials",            adminMiddleware, brandFinancialCtrl.getBrandFinancials);
router.post("/schedules",                           adminMiddleware, scheduleController.createSchedule);
router.get("/schedules",                            adminMiddleware, scheduleController.getAllSchedules);
router.post("/schedules/generate",                  adminMiddleware, scheduleController.manualGenerateTrips);
router.get("/schedules/:id",                        adminMiddleware, scheduleController.getScheduleById);
router.patch("/schedules/:id",                      adminMiddleware, scheduleController.updateSchedule);
router.patch("/schedules/:id/activate",             adminMiddleware, scheduleController.activateSchedule);
router.patch("/schedules/:id/go-live",              adminMiddleware, scheduleController.goLiveSchedule);
router.patch("/schedules/:id/suspend",              adminMiddleware, scheduleController.suspendSchedule);
router.patch("/schedules/:id/resume",               adminMiddleware, scheduleController.resumeSchedule);
router.post("/schedules/:id/version",               adminMiddleware, scheduleController.createScheduleVersion);
router.patch("/schedules/:id/deactivate",           adminMiddleware, scheduleController.deactivateSchedule);
router.delete("/schedules/:id",                     adminMiddleware, scheduleController.deleteSchedule);
router.get("/schedules/:id/trips",                  adminMiddleware, scheduleController.getTripsBySchedule);
router.post("/schedules/:id/burst",                 adminMiddleware, scheduleController.burstGenerateTrips);
router.get("/brands/:brandId/schedules",            adminMiddleware, scheduleController.getSchedulesByBrand);
router.patch("/trips/:id/cancel",                   adminMiddleware, tripExceptionCtrl.cancelTrip);
router.patch("/trips/:id/reschedule",               adminMiddleware, tripExceptionCtrl.rescheduleTrip);
router.post("/schedules/:id/cancel-range",          adminMiddleware, tripExceptionCtrl.cancelDateRange);
router.post("/schedules/:id/extra-run",             adminMiddleware, tripExceptionCtrl.createExtraRun);
router.get("/transactions",      adminMiddleware, transactionCtrl.getAllTransactions);
router.get("/transactions/:id",  adminMiddleware, transactionCtrl.getTransactionById);
const disputedPayments = require("../../controllers/adminController/disputedPaymentsController.js");
router.get("/disputes",                          adminMiddleware, disputedPayments.getDisputedPayments);
router.patch("/disputes/:transactionId/resolve", adminMiddleware, disputedPayments.resolveDispute);
const platformConfigCtrl = require("../../controllers/adminController/platformConfigController.js");
router.get("/platform-config",              adminMiddleware, platformConfigCtrl.listConfigs);
router.get("/platform-config/:key",         adminMiddleware, platformConfigCtrl.getConfig);
router.put("/platform-config/:key",         adminMiddleware, platformConfigCtrl.updateConfig);
const scratchThemeCtrl = require("../../controllers/adminController/scratchThemeController.js");
router.get("/scratch-themes",                    adminMiddleware, scratchThemeCtrl.listThemes);
router.post("/scratch-themes",                   adminMiddleware, scratchThemeCtrl.createTheme);
router.patch("/scratch-themes/:themeId",          adminMiddleware, scratchThemeCtrl.updateTheme);
router.patch("/scratch-themes/:themeId/image",    adminMiddleware, scratchThemeCtrl.replaceThemeImage);
router.patch("/scratch-themes/:themeId/toggle",   adminMiddleware, scratchThemeCtrl.toggleTheme);
router.delete("/scratch-themes/:themeId",         adminMiddleware, scratchThemeCtrl.deleteTheme);
const documentProxy = require("../../src/modules/shared/document-proxy");
router.get("/documents/view", adminMiddleware, documentProxy.viewDocument);
module.exports = router;
