const { S3Client, GetObjectCommand } = require("@aws-sdk/client-s3");

const s3Client = new S3Client({
    region: process.env.AWS_REGION,
    credentials: {
        accessKeyId: process.env.AWS_ACCESS_KEY_ID,
        secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
    },
});

/**
 * ── Secure Document Proxy ──────────────────────────────────────────────────────
 *
 * Streams an S3 object directly to the browser — the presigned URL (with AWS
 * credentials and signature) NEVER leaves the server.
 *
 * The frontend calls:
 *   GET /api/admin/documents/view?key=owners/{id}/kyc/company-registration/123.pdf
 *
 * Security:
 *   - Protected by adminMiddleware (valid JWT required)
 *   - Only allows keys that belong to known S3 prefixes (allowlist)
 *   - No direct S3 URL is exposed to the client at any point
 *   - Streams the file — no temp file is written to disk
 *
 * @route  GET /api/admin/documents/view
 * @access Admin only (adminMiddleware)
 */
const viewDocument = async (req, res) => {
    try {
        const { key } = req.query;

        if (!key || typeof key !== "string") {
            return res.status(400).json({
                success: false,
                message: "Missing required query parameter: key",
            });
        }

        console.log("[documentProxy] raw key received:", JSON.stringify(key.substring(0, 120)));

        // ── Normalise: extract path from full S3 URLs (legacy data) ──────────
        // Some older records stored full presigned URLs instead of object keys.
        // Example: "https://bucket.s3.region.amazonaws.com/owners/xxx/kyc/..."
        // Strip the host + query string and use only the path as the key.
        let resolvedKey = key;
        if (key.startsWith("http://") || key.startsWith("https://")) {
            try {
                const parsed = new URL(key);
                // pathname starts with "/" — remove leading slash
                resolvedKey = parsed.pathname.replace(/^\//, "");
                console.log("[documentProxy] legacy URL → resolved key:", resolvedKey.substring(0, 80));
            } catch {
                console.warn("[documentProxy] Could not parse URL key:", key.substring(0, 80));
            }
        }

        // ── Security: Strict allowlist of valid key prefixes ──────────────────
        // Must cover every prefix pattern generated by buildS3Path() in s3Service.js:
        //   owners/{id}/kyc/...                   → Bus owner KYC docs
        //   owners/{id}/brands/{id}/fleets/...    → Fleet images & documents
        //   brands/{id}/drivers/{id}/...          → Driver KYC documents
        //   disputes/...                          → Dispute proof attachments
        //   platform/...                          → Platform assets (scratch themes)
        const ALLOWED_PREFIXES = [
            "owners/",
            "brands/",
            "agents/",      // Agent KYC documents
            "disputes/",
            "platform/",
            "agent_kyc/",
            "bus_owner_docs/", // Legacy path for older bus owner documents
            "misc/",
        ];

        const isAllowed = ALLOWED_PREFIXES.some((prefix) => resolvedKey.startsWith(prefix));
        console.log("[documentProxy] resolvedKey:", resolvedKey.substring(0, 80), "| allowed:", isAllowed);
        if (!isAllowed) {
            console.warn("[documentProxy] BLOCKED — resolvedKey does not match any prefix:", resolvedKey.substring(0, 100));
            return res.status(403).json({
                success: false,
                message: "Access denied: key path is not permitted.",
                debug_key_start: resolvedKey.substring(0, 80),
            });
        }


        // ── Fetch the object from S3 and stream to client ─────────────────────
        const command = new GetObjectCommand({
            Bucket: process.env.AWS_S3_BUCKET_NAME,
            Key: resolvedKey,
        });

        const s3Response = await s3Client.send(command);

        // Forward the content type so the browser knows how to display it
        const contentType = s3Response.ContentType || "application/octet-stream";
        res.setHeader("Content-Type", contentType);

        // Suggest the filename from the key (last segment, no path)
        const filename = resolvedKey.split("/").pop() || "document";
        res.setHeader("Content-Disposition", `inline; filename="${filename}"`);

        if (s3Response.ContentLength) {
            res.setHeader("Content-Length", s3Response.ContentLength);
        }

        // Cache for 5 minutes in the browser (admin session only)
        res.setHeader("Cache-Control", "private, max-age=300");

        // Pipe the S3 readable stream directly to the HTTP response
        s3Response.Body.pipe(res);

    } catch (error) {
        // Log full error for debugging
        console.error("[documentProxy] S3 error:", {
            name: error.name,
            code: error.Code,
            message: error.message,
            statusCode: error.$metadata?.httpStatusCode,
            resolvedKey: req.query?.key?.substring(0, 100),
        });

        // S3 NoSuchKey — the document doesn't exist
        if (error.name === "NoSuchKey" || error.$metadata?.httpStatusCode === 404) {
            return res.status(404).json({
                success: false,
                message: "Document not found. It may have been deleted or the key is incorrect.",
                debug_key: req.query?.key?.substring(0, 100),
            });
        }

        console.error("[documentProxy] viewDocument error:", error);
        return res.status(500).json({
            success: false,
            message: "Failed to retrieve document.",
        });
    }
};

module.exports = { viewDocument };
