'use strict';

/**
 * document-proxy.policy.js
 *
 * Pure business rules for the document proxy — no AWS SDK, no Express objects.
 * Tests can import and exercise this module without any infrastructure.
 */

/**
 * Exact allowlist of S3 key prefixes that this proxy will serve.
 * Must mirror every prefix pattern generated by buildS3Path() in s3Service.js.
 *
 *   owners/{id}/kyc/...                  → Bus owner KYC docs
 *   owners/{id}/brands/{id}/fleets/...   → Fleet images & documents
 *   brands/{id}/drivers/{id}/...         → Driver KYC documents
 *   disputes/...                         → Dispute proof attachments
 *   platform/...                         → Platform assets (scratch themes)
 *   agents/...                           → Agent KYC documents
 *   agent_kyc/...                        → Legacy agent KYC path
 *   misc/...                             → Miscellaneous legacy assets
 */
const ALLOWED_PREFIXES = [
    'owners/',
    'brands/',
    'agents/',
    'disputes/',
    'platform/',
    'agent_kyc/',
    'misc/',
];

/**
 * Normalise a raw key received from the query string.
 *
 * Legacy records stored full presigned S3 URLs instead of object keys.
 * Strip the host + query string and return only the path (without leading slash).
 * If the URL cannot be parsed, return the original raw value unchanged.
 *
 * @param {string} rawKey
 * @returns {{ resolvedKey: string, wasUrl: boolean, parseFailed: boolean }}
 */
function normaliseKey(rawKey) {
    if (!rawKey.startsWith('http://') && !rawKey.startsWith('https://')) {
        return { resolvedKey: rawKey, wasUrl: false, parseFailed: false };
    }

    try {
        const parsed = new URL(rawKey);
        // pathname starts with "/" — remove the leading slash
        const resolvedKey = parsed.pathname.replace(/^\//, '');
        return { resolvedKey, wasUrl: true, parseFailed: false };
    } catch {
        return { resolvedKey: rawKey, wasUrl: true, parseFailed: true };
    }
}

/**
 * Return true when the resolved key starts with one of the allowed prefixes.
 *
 * @param {string} resolvedKey
 * @returns {boolean}
 */
function isKeyAllowed(resolvedKey) {
    if (!resolvedKey || typeof resolvedKey !== 'string') return false;
    // Bus-owner KYC must go through the record-bound KYC read endpoint, which
    // enforces owner/admin authorization and malware-scan quarantine status.
    if (/^owners\/[^/]+\/kyc\//.test(resolvedKey)) return false;
    if (resolvedKey.includes('/fleets/') || resolvedKey.startsWith('fleet-documents/') || resolvedKey.startsWith('fleet-images/')) {
        return false;
    }
    return ALLOWED_PREFIXES.some((prefix) => resolvedKey.startsWith(prefix));
}

module.exports = {
    ALLOWED_PREFIXES,
    normaliseKey,
    isKeyAllowed,
};
