const mongoose = require("mongoose");

/**
 * SCHEDULE MODEL — The Source of Truth for Repeating Bus Services
 *
 * Architecture:
 *   Schedule  →  Trip (daily instances, auto-generated by CRON)
 *
 * A Schedule answers: "What service does this bus run, on which route,
 * at what time, on which days?"
 *
 * A Trip answers: "Did that service actually run on a specific date?
 * What were the seat bookings? Who was the driver?"
 *
 * KEY DESIGN DECISIONS:
 *  1. Schedule is brand-owned — an OperatorBrand runs the schedule on behalf of an owner.
 *  2. Schedule references the NEW platform registry (variantId) — not the legacy BusRoute.
 *  3. A Schedule can only be ACTIVE if its fleet is APPROVED and ACTIVE.
 *  4. Changing a schedule does NOT retroactively alter past trips.
 *  5. Suspending a schedule stops future trip generation but doesn't cancel past ones.
 */
const scheduleSchema = new mongoose.Schema(
    {
        // ─── CHAIN LINKS ──────────────────────────────────────────────────────
        // Every entity in the chain must know its parent.

        // The Operator Brand running this service
        brandId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "OperatorBrand",
            required: true,
            index: true,
        },

        // The Bus Owner (denormalized from brand for fast queries)
        ownerId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User",
            required: true,
            index: true,
        },

        // The specific vehicle assigned to this schedule
        busId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Buse",
            required: true,
            index: true,
        },

        // ─── ROUTE ────────────────────────────────────────────────────────────
        // The platform registry variant this schedule operates on.
        // This links into the new 5-layer route system.
        variantId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "RouteVariant",
            default: null,
            index: true,
        },

        // The operator's specific route configuration on top of the variant
        // (defines which stops they serve, boarding points, timing)
        operatorRouteConfigId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "OperatorRouteConfig",
            default: null,
        },

        // ─── DRIVER ───────────────────────────────────────────────────────────
        // Default driver assigned to this schedule.
        // Individual trips can override this (e.g., driver sick, substitute assigned).
        // Refs DriverProfile (NOT User) — drivers are brand-scoped compliance entities.
        driverId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "DriverProfile",
            default: null,
        },

        // ─── SEAT LAYOUT ──────────────────────────────────────────────────────
        // Legacy: previously linked to SeatTemplate.
        // Now optional. The system uses the bus's embedded seatConfig.
        seatTemplateId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "SeatTemplate",
            default: null,
        },

        // ─── TIMING ───────────────────────────────────────────────────────────
        // 24-hour "HH:MM" format — unambiguous, timezone-independent
        departureTime: {
            type: String,
            required: true,
            match: [/^\d{2}:\d{2}$/, "Departure time must be in HH:MM format (e.g., 17:00)"],
        },

        // Estimated arrival time — may span into next day (overnight trips)
        arrivalTime: {
            type: String,
            required: true,
            match: [/^\d{2}:\d{2}$/, "Arrival time must be in HH:MM format (e.g., 05:30)"],
        },

        // Whether this is a day or night service (for display grouping)
        shift: {
            type: String,
            enum: ["day", "night"],
            required: true,
        },

        // ─── RECURRENCE ───────────────────────────────────────────────────────
        recurrence: {
            type: String,
            enum: ["DAILY", "WEEKLY", "CUSTOM"],
            required: true,
            default: "DAILY",
        },

        // For WEEKLY/CUSTOM: which days of the week this runs
        // 0 = Sunday, 1 = Monday, ..., 6 = Saturday
        // Example: Mon-Fri only = [1, 2, 3, 4, 5]
        daysOfWeek: {
            type: [Number],
            default: [],
            validate: {
                validator: (arr) => arr.every((d) => d >= 0 && d <= 6),
                message: "daysOfWeek must contain values 0–6 (Sun–Sat)",
            },
        },

        // ─── EFFECTIVE PERIOD ─────────────────────────────────────────────────
        // The schedule generates trips only within this window.
        // effectiveFrom is required — you must declare when this service starts.
        effectiveFrom: {
            type: Date,
            required: true,
        },

        // Optional end date — null means "runs indefinitely until suspended"
        effectiveUntil: {
            type: Date,
            default: null,
        },

        // ─── FARE ─────────────────────────────────────────────────────────────
        // Optional: override the fleet/route default fare for this specific schedule
        // If null, the system falls back to FareRule → Route base price
        fareOverride: {
            type: Number,
            default: null,
            min: 0,
        },

        // ─── STATUS ───────────────────────────────────────────────────────────
        // DRAFT       → Created but not yet reviewed/activated
        // ACTIVE      → Generating trips daily via CRON
        // SUSPENDED   → Temporarily paused — no new trips generated
        // INACTIVE    → Permanently stopped (soft delete)
        status: {
            type: String,
            enum: ["DRAFT", "ACTIVE", "SUSPENDED", "INACTIVE"],
            default: "DRAFT",
            index: true,
        },

        // ─── AUDIT ────────────────────────────────────────────────────────────
        createdBy: {
            type: String,
            enum: ["ADMIN", "OWNER"],
            default: "ADMIN",
        },

        activatedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Admin",
            default: null,
        },
        activatedAt: {
            type: Date,
            default: null,
        },

        suspendedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Admin",
            default: null,
        },
        suspendedAt: {
            type: Date,
            default: null,
        },
        suspensionReason: {
            type: String,
            default: null,
        },

        // Optional: date on which this schedule auto-resumes from SUSPENDED.
        // If null, the suspension is indefinite and requires a manual /resume call.
        // The daily CRON sweeps for SUSPENDED schedules with suspendUntil <= today
        // and auto-flips them back to ACTIVE.
        suspendUntil: {
            type: Date,
            default: null,
        },

        // Audit trail for resume operations
        resumedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Admin",
            default: null,
        },
        resumedAt: {
            type: Date,
            default: null,
        },

        // Internal admin notes
        notes: {
            type: String,
            default: null,
            trim: true,
        },

        // ─── TRIP GENERATION WINDOW ───────────────────────────────────────────
        // How many days ahead to pre-generate trips from this schedule.
        // CRON maintains a rolling window of this many days at all times.
        // On schedule activation: burst-generate this many days immediately.
        // Industry standard: 60 days for Nepal intercity routes.
        advanceGenerationDays: {
            type: Number,
            default: 60,
            min: 7,
            max: 180,
        },

        // ─── BOOKING WINDOW ───────────────────────────────────────────────────
        // How many days before a trip passengers can start booking.
        // Typically matches advanceGenerationDays but can be shorter.
        advanceBookingDays: {
            type: Number,
            default: 60,
            min: 1,
            max: 180,
        },
        // How many hours before departure the booking window closes.
        // Prevents last-minute chaos; 2 hours is industry standard.
        bookingCutoffHours: {
            type: Number,
            default: 2,
            min: 0,
            max: 72,
        },

        // ─── RETURN TRIP LINKING ──────────────────────────────────────────────
        // For TURNAROUND routes: links this outbound schedule to its return.
        // Both schedules reference each other via this field.
        // Suspending one schedule warns about the linked counterpart.
        returnScheduleId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Schedule",
            default: null,
        },

        // ─── TEMPORAL VERSIONING ─────────────────────────────────────────────
        // Industry standard: active schedules are IMMUTABLE CONTRACTS.
        // To change timings, create a NEW version with a future effectiveFrom.
        // The old version's effectiveUntil is auto-set to effectiveFrom - 1 day.
        //
        // versionNumber: 1 = original, 2 = first change, 3 = second change...
        // parentScheduleId: links a version back to the schedule it supersedes.
        // pendingVersionId: forward reference — "this schedule is being replaced by..."
        versionNumber: {
            type: Number,
            default: 1,
            min: 1,
        },
        parentScheduleId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Schedule",
            default: null,
        },
        pendingVersionId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Schedule",
            default: null,
        },

        // ─── OPERATIONAL PATTERN ─────────────────────────────────────────────
        // TURNAROUND: one bus does both directions the same day
        //   (departs KTM 6AM, arrives PKR 12PM, layover, returns PKR 1PM)
        // RELAY: bus parks at destination overnight; different bus (or next day
        //   same bus) handles the return. Return is a separate schedule entity.
        operationalModel: {
            type: String,
            enum: ["TURNAROUND", "RELAY"],
            default: "TURNAROUND",
        },
        // Minimum rest at destination before return departure (TURNAROUND only).
        // Enforced during first-departure-direction logic in CRON.
        layoverMinutes: {
            type: Number,
            default: 60,
            min: 15,
            max: 720,
        },
    },
    { timestamps: true }
);

// ─── INDEXES ──────────────────────────────────────────────────────────────────
// CRON query: find all ACTIVE schedules that should run today
scheduleSchema.index({ status: 1, effectiveFrom: 1, effectiveUntil: 1 });

// Brand dashboard: all schedules for a brand
scheduleSchema.index({ brandId: 1, status: 1 });

// Fleet schedule view: all schedules for a specific bus
scheduleSchema.index({ busId: 1, status: 1 });

// Owner-level view: all schedules across all their brands
scheduleSchema.index({ ownerId: 1, status: 1, createdAt: -1 });

// Index removed: a bus CAN have the same departure time if operating on alternating days or different legs (relay).

// Return trip lookup: quickly find the counterpart of a linked schedule
scheduleSchema.index({ returnScheduleId: 1 }, { sparse: true });

module.exports = mongoose.model("Schedule", scheduleSchema);
