const mongoose = require("mongoose");

const tripSchema = new mongoose.Schema(
  {
    tripId: {
      type: String,
      unique: true,
      index: true, // e.g., TRIP-KTM-BRT-001
    },
    busId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Buse", // Reference to the Fleet (Fleet model uses "Buse" as model name)
      required: true,
    },
    routeId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "BusRoute",
      required: true,
    },
    ownerId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    driverId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",       // role: "driver"
      default: null,
    },
    tripDate: {
      type: String,
      required: true,
    },
    departureTime: {
      type: String,
      required: true,
    },
    arrivalTime: {
      type: String,
      required: true,
    },
    // Price Override: If null, use Route.basePrice
    tripFare: {
      type: Number,
      default: null,
    },
    // Seat template reference for this trip
    seatTemplateId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "SeatTemplate",
      required: true,
    },
    // Automation & Linking
    isAutoGenerated: {
      type: Boolean,
      default: false,
    },
    templateId: {
      type: String, // Reference to a template if automated
      default: null,
    },
    returnTripLinked: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Trip",
      default: null,
    },
    status: {
      type: String,
      enum: ["scheduled", "boarding", "in-transit", "completed", "cancelled"],
      default: "scheduled",
    },
    recurrence: {
      type: String,
      enum: ["none", "daily", "weekly", "custom"],
      default: "none",
    },
    shift: {
      type: String,
      enum: ["day", "night"],
      required: true,
    },
    daysOfWeek: [
      {
        type: Number, // 0-6 (Sun-Sat)
      },
    ],
    autoGenerateUntil: {
      type: Date,
      default: null,
    },
    isActive: {
      type: Boolean,
      default: true,
    },
  },
  { timestamps: true }
);

// Indexes for performance
tripSchema.index({ departureTime: 1 });
tripSchema.index({ busId: 1, departureTime: 1 });

module.exports = mongoose.models.Trip || mongoose.model("Trip", tripSchema);
