const mongoose = require("mongoose");

const tripSchema = new mongoose.Schema(
  {
    tripId: {
      type: String,
      unique: true,
      index: true, // e.g., TRIP-KTM-BRT-001
    },
    busId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Buse", // Reference to the Fleet (Fleet model uses "Buse" as model name)
      required: true,
    },
    routeId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "BusRoute",
      required: false, // Legacy field — kept for existing trips only
    },
    // [NEW] Registry-aligned: points to a specific RouteVariant (Layer 2)
    // New trips should always populate this instead of routeId
    variantId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "RouteVariant",
      default: null,
    },
    ownerId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    // [CHAIN LINK] Brand this trip belongs to (OperatorBrand)
    // Required for all new trips. Enables brand-level financial aggregation
    // without multi-collection joins: Trip.brandId → OperatorBrand directly.
    brandId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "OperatorBrand",
        default: null,
        index: true,
    },
    driverId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "DriverProfile",  // brand-scoped compliance entity (NOT User)
      default: null,
    },
    // Audit log for driver assignments
    driverAssignmentLog: [{
      driverId: { type: mongoose.Schema.Types.ObjectId, ref: "DriverProfile" },
      assignedAt: { type: Date, default: Date.now },
      assignedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
      reason: { type: String }
    }],
    tripDate: {
      type: Date,      // Always store as UTC Date — display in client timezone
      required: true,
    },
    departureTime: {
      type: String,
      required: true,
    },
    actualDepartureTime: {
      type: Date,
      default: null,
    },
    arrivalTime: {
      type: String,
      required: true,
    },
    actualArrivalTime: {
      type: Date,
      default: null,
    },
    // Price Override: If null, use Route.basePrice
    tripFare: {
      type: Number,
      default: null,
    },
    // Calculated from schedule.bookingCutoffHours during generation
    bookingClosesAt: {
      type: Date,
      required: true,
    },
    // Seat template reference for this trip.
    // Optional in V2 — the bus's own embedded seatConfig is used when this is null.
    // Legacy trips may still reference an external SeatTemplate document.
    seatTemplateId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "SeatTemplate",
      default: null,
    },
    // ─── AUTOMATION & CHAIN LINKING ────────────────────────────────────────
    // If this trip was generated by the CRON from a Schedule, scheduleId links
    // back to the Schedule that produced it. This is the clean chain:
    //   Schedule → Trip (one-to-many, date-based instances)
    scheduleId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Schedule",
      default: null,
      index: true,
    },
    // ─── DIRECTION (baked at generation time) ─────────────────────────────
    // Pre-computed so the UI never needs variant→corridor→stop chain resolution.
    // Example: "Kathmandu → Pokhara" or "Pokhara → Kathmandu"
    directionLabel: {
      type: String,
      default: null,
    },
    fromStopName: {
      type: String,
      default: null,
    },
    toStopName: {
      type: String,
      default: null,
    },

    isAutoGenerated: {
      type: Boolean,
      default: false,
    },
    // Legacy: string-based templateId (kept for backward-compat with old trips)
    // New trips use scheduleId (ObjectId) instead.
    templateId: {
      type: String,
      default: null,
    },
    returnTripLinked: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Trip",
      default: null,
    },
    status: {
      type: String,
      enum: ["scheduled", "boarding", "in-transit", "completed", "cancelled"],
      default: "scheduled",
    },
    cancelledBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },
    cancellationReason: {
      type: String,
      default: null,
    },
    cancelledAt: {
      type: Date,
      default: null,
    },

    // ─── TRIP-LEVEL EXCEPTIONS (GTFS calendar_dates pattern) ──────────────────
    // Allows one-off changes to a single trip without altering the master schedule.
    //
    //   NONE        = normal generated trip (default)
    //   CANCELLED   = removed on this date only (e.g. bus breakdown, holiday)
    //   RESCHEDULED = timings changed for this date only (e.g. 2hrs late due to road work)
    //   EXTRA_RUN   = one-off trip added on a date not in the regular schedule
    //
    exceptionType: {
      type: String,
      enum: ["NONE", "CANCELLED", "RESCHEDULED", "EXTRA_RUN"],
      default: "NONE",
    },
    // For RESCHEDULED trips: preserve the original timings for audit display
    originalDepartureTime: {
      type: String,
      default: null,
    },
    originalArrivalTime: {
      type: String,
      default: null,
    },
    rescheduleReason: {
      type: String,
      default: null,
    },
    rescheduledBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },
    rescheduledAt: {
      type: Date,
      default: null,
    },
    recurrence: {
      type: String,
      enum: ["none", "daily", "weekly", "custom"],
      default: "none",
    },
    shift: {
      type: String,
      enum: ["day", "night"],
      required: true,
    },
    daysOfWeek: [
      {
        type: Number, // 0-6 (Sun-Sat)
      },
    ],
    autoGenerateUntil: {
      type: Date,
      default: null,
    },
    isActive: {
      type: Boolean,
      default: true,
    },
  },
  { timestamps: true }
);

// Indexes for performance
tripSchema.index({ departureTime: 1 });
tripSchema.index({ busId: 1, tripDate: 1 });                    // Fleet schedule view
tripSchema.index({ routeId: 1, tripDate: 1, status: 1 });       // searchTrips core query
tripSchema.index({ ownerId: 1, status: 1, tripDate: -1 });      // Bus owner trips list
tripSchema.index({ brandId: 1, status: 1, tripDate: -1 });      // Brand-level financial queries
tripSchema.index({ scheduleId: 1, tripDate: -1 });                     // Schedule → Trips lookup
tripSchema.index({ status: 1, recurrence: 1, autoGenerateUntil: 1 }); // Legacy CRON query

module.exports = mongoose.models.Trip || mongoose.model("Trip", tripSchema);
