"use strict";

const Schedule = require("../../../../models/scheduleModel.js");
const Trip = require("../../../../models/tripModel.js");

const getSchedulesByBrand = (brandId, filters = {}) => {
  const query = { brandId };
  if (filters.status) query.status = filters.status;
  return Schedule.find(query)
    .populate("busId", "busName busNumber busType vehicleType")
    .populate({
      path: "variantId",
      select: "name direction type",
      populate: {
        path: "corridorId",
        select: "code originId destinationId",
        populate: [
          { path: "originId", select: "name code" },
          { path: "destinationId", select: "name code" },
        ],
      },
    })
    .populate("driverId", "fullName phone")
    .populate("seatTemplateId", "templateName totalSeats")
    .sort({ createdAt: -1 })
    .lean();
};

const getSchedulesByOwner = (ownerId, filters = {}) => {
  const query = { ownerId };
  if (filters.status) query.status = filters.status;
  if (filters.brandId) query.brandId = filters.brandId;
  return Schedule.find(query)
    .populate("brandId", "brandName")
    .populate("busId", "busName busNumber")
    .populate("driverId", "fullName phone")
    .sort({ brandId: 1, departureTime: 1 })
    .lean();
};

const getTripsBySchedule = (scheduleId, filters = {}) => {
  const query = { scheduleId };
  if (filters.status) query.status = filters.status;
  if (filters.from && filters.to) {
    query.tripDate = {
      $gte: new Date(filters.from),
      $lte: new Date(filters.to),
    };
  }
  return Trip.find(query)
    .select(
      "tripId tripDate status driverId departureTime isAutoGenerated createdAt"
    )
    .populate("driverId", "fullName phone")
    .sort({ tripDate: -1 })
    .lean();
};

const getScheduleById = async (scheduleId) => {
  const schedule = await Schedule.findById(scheduleId)
    .populate("brandId", "brandName commissionRate")
    .populate(
      "busId",
      "busName busNumber busType vehicleType approvalStatus status fleetId"
    )
    .populate("variantId", {
      path: "corridorId",
      populate: [
        { path: "originId", select: "name code" },
        { path: "destinationId", select: "name code" },
      ],
    })
    .populate("driverId", "fullName phone")
    .populate("seatTemplateId", "templateName totalSeats")
    .lean();
  if (!schedule) throw new Error("Schedule not found.");
  return schedule;
};

const getAllSchedules = async ({
  page = 1,
  limit = 30,
  status,
  brandId,
  busId,
} = {}) => {
  const query = {};
  if (status && status !== "all") query.status = status;
  if (brandId) query.brandId = brandId;
  if (busId) query.busId = busId;
  const [schedules, total] = await Promise.all([
    Schedule.find(query)
      .populate("brandId", "brandName")
      .populate("busId", "busName busNumber")
      .populate("driverId", "fullName phone")
      .sort({ createdAt: -1 })
      .skip((page - 1) * limit)
      .limit(limit)
      .lean(),
    Schedule.countDocuments(query),
  ]);
  return {
    schedules,
    pagination: { total, page, limit, totalPages: Math.ceil(total / limit) },
  };
};

module.exports = {
  getSchedulesByBrand,
  getSchedulesByOwner,
  getTripsBySchedule,
  getScheduleById,
  getAllSchedules,
};
